import React from 'react';
import ScoreCircle from './ScoreCircle';
import CheckCard from './CheckCard';
import { Globe, Clock, CheckCircle2, XCircle, AlertTriangle, MinusCircle, Download } from 'lucide-react';
import { RadarChart, PolarGrid, PolarAngleAxis, Radar, ResponsiveContainer, Tooltip } from 'recharts';

const STATUS_LABEL = {
  compliant: 'Compliant',
  partial: 'Partially Compliant',
  'non-compliant': 'Non-Compliant'
};

export default function AuditResult({ audit }) {
  const { url, domain, pageTitle, overallScore, overallStatus, checks, summary, scanDate } = audit;

  const radarData = checks.filter(c => c.status !== 'na').map(c => ({
    subject: c.section.split(' ').slice(0, 2).join(' '),
    score: c.score,
    fullMark: 100
  }));

  const date = scanDate ? new Date(scanDate).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : '—';

  const handleDownload = () => {
    const sep = '='.repeat(60);
    const thin = '-'.repeat(60);

    const lines = [
      sep,
      '  DPDP ACT 2023 — COMPLIANCE AUDIT REPORT',
      sep,
      '',
      `  Website  : ${url}`,
      `  Domain   : ${domain}`,
      `  Scanned  : ${date}`,
      `  Score    : ${overallScore} / 100`,
      `  Status   : ${STATUS_LABEL[overallStatus] || overallStatus}`,
      '',
      thin,
      '  SUMMARY',
      thin,
      `  ✅ Passed   : ${summary?.passed ?? 0}`,
      `  ❌ Failed   : ${summary?.failed ?? 0}`,
      `  ⚠️  Warnings : ${summary?.warnings ?? 0}`,
      `  —  N/A     : ${summary?.notApplicable ?? 0}`,
      '',
      thin,
      '  DETAILED CHECKS',
      thin,
      '',
      ...checks.map(c => {
        const icon = { pass: '✅', fail: '❌', warn: '⚠️ ', na: '—' }[c.status] || '—';
        const block = [
          `  ${icon}  ${c.section}`,
          `      Law    : ${c.law}`,
          `      Score  : ${c.score}/100  [${c.status.toUpperCase()}]`,
          `      About  : ${c.description}`,
          `      Result : ${c.details}`,
        ];
        if (c.evidence && c.evidence.length) {
          block.push(`      Signals:`);
          c.evidence.forEach(e => block.push(`               ${e}`));
        }
        if (c.recommendation) {
          // Word-wrap recommendation at ~70 chars
          const words = c.recommendation.split(' ');
          const wrapped = [];
          let line = '';
          words.forEach(w => {
            if ((line + w).length > 68) { wrapped.push(line.trim()); line = ''; }
            line += w + ' ';
          });
          if (line.trim()) wrapped.push(line.trim());
          block.push(`      Fix    :`);
          wrapped.forEach(l => block.push(`               ${l}`));
        }
        block.push('');
        return block.join('\n');
      }),
      thin,
      '  DISCLAIMER',
      thin,
      '  This report is generated by automated heuristic analysis.',
      '  It is for educational purposes only and does not constitute',
      '  legal advice. Consult a qualified data protection professional',
      '  for full DPDP Act compliance assessment.',
      '',
      `  Report generated on ${new Date().toLocaleString('en-IN')}`,
      sep,
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `dpdp-report-${domain.replace(/\./g, '-')}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="result-panel">
      {/* Score header */}
      <div className="score-header">
        <ScoreCircle score={overallScore} status={overallStatus} />
        <div className="score-info">
          <h2>{pageTitle || domain}</h2>
          <div className="domain-tag">{domain}</div>
          <div className="score-meta">
            <div className="meta-chip">
              <span className={`status-badge badge-${overallStatus}`}>
                {STATUS_LABEL[overallStatus] || overallStatus}
              </span>
            </div>
            <div className="meta-chip">
              <Globe size={14} style={{ color: 'var(--accent)' }} />
              <span style={{ fontSize: 12, fontFamily: 'var(--font-mono)', wordBreak: 'break-all' }}>{url}</span>
            </div>
            <div className="meta-chip">
              <Clock size={14} style={{ color: 'var(--text-3)' }} />
              <span style={{ fontSize: 12, color: 'var(--text-3)', fontFamily: 'var(--font-mono)' }}>{date}</span>
            </div>
          </div>
          <div className="score-meta" style={{ marginTop: 12 }}>
            <div className="meta-chip"><span className="dot dot-pass" /><CheckCircle2 size={12} style={{ color: 'var(--green)' }} />{summary?.passed} Passed</div>
            <div className="meta-chip"><span className="dot dot-fail" /><XCircle size={12} style={{ color: 'var(--red)' }} />{summary?.failed} Failed</div>
            <div className="meta-chip"><span className="dot dot-warn" /><AlertTriangle size={12} style={{ color: 'var(--yellow)' }} />{summary?.warnings} Warnings</div>
            <div className="meta-chip"><span className="dot dot-na" /><MinusCircle size={12} style={{ color: 'var(--text-3)' }} />{summary?.notApplicable} N/A</div>
          </div>
        </div>
      </div>

      {/* Radar chart */}
      {radarData.length > 0 && (
        <div style={{
          background: 'var(--bg-card)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius)', padding: '24px', marginBottom: 24
        }}>
          <h3 style={{ fontSize: 14, fontWeight: 600, marginBottom: 20, color: 'var(--text-2)' }}>
            Compliance Radar
          </h3>
          <ResponsiveContainer width="100%" height={280}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="rgba(255,255,255,0.05)" />
              <PolarAngleAxis dataKey="subject" tick={{ fill: 'var(--text-3)', fontSize: 11 }} />
              <Radar name="Score" dataKey="score" stroke="#3b82f6" fill="#3b82f6" fillOpacity={0.15} strokeWidth={2} />
              <Tooltip
                contentStyle={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 8 }}
                labelStyle={{ color: 'var(--text)' }} itemStyle={{ color: 'var(--accent)' }}
              />
            </RadarChart>
          </ResponsiveContainer>
        </div>
      )}

      {/* Download + heading */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <h3 style={{ fontSize: 16, fontWeight: 600, color: 'var(--text-2)' }}>
          Detailed Compliance Checks
        </h3>
        <button onClick={handleDownload} style={{
          display: 'flex', alignItems: 'center', gap: 8,
          padding: '10px 20px', background: 'var(--accent)',
          border: 'none', borderRadius: 8, color: '#fff',
          fontSize: 13, fontWeight: 600, cursor: 'pointer',
          fontFamily: 'var(--font-display)', transition: 'background 0.2s'
        }}
          onMouseOver={e => e.currentTarget.style.background = 'var(--accent-2)'}
          onMouseOut={e => e.currentTarget.style.background = 'var(--accent)'}
        >
          <Download size={14} /> Download Report
        </button>
      </div>

      <div className="checks-grid">
        {checks && checks.map((check, i) => (
          <CheckCard key={check.id || i} check={check} pageText={audit.pageText || ''} />
        ))}
      </div>
    </div>
  );
}